export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';
export const STORE_CUSTOM_SURVEY_FORM = 'STORE_CUSTOM_SURVEY_FORM';
export const SAVE_USER_SURVEY_FORM_SUCCESS = 'SAVE_USER_SURVEY_FORM_SUCCESS';
export const SAVE_USER_SURVEY_FORM_FAIL = 'SAVE_USER_SURVEY_FORM_FAIL';
